/**
 * Terminology
 * Terminology API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NdcDto } from '../models/NdcDto';
import { HttpFile } from '../http/http';

export class NdcControllerSearch200Response {
    'result'?: Array<NdcDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "result",
            "baseName": "result",
            "type": "Array<NdcDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NdcControllerSearch200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

