/**
 * Terminology
 * Terminology API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class NdcDto {
    'id': string;
    'productNdc': string;
    'productType'?: string;
    'genericName'?: string;
    'labelerName'?: string;
    'brandName'?: string;
    'brandNameSuffix'?: string;
    'listingExpirationDate'?: Date;
    'marketingCategory'?: string;
    'dosageForm'?: string;
    'marketingStartDate'?: Date;
    'marketingEndDate'?: Date;
    'applicationNumber'?: string;
    'pharmClass': Array<string>;
    'route': Array<string>;
    'activeIngredients'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "productNdc",
            "baseName": "product_ndc",
            "type": "string",
            "format": ""
        },
        {
            "name": "productType",
            "baseName": "product_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "genericName",
            "baseName": "generic_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "labelerName",
            "baseName": "labeler_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "brandName",
            "baseName": "brand_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "brandNameSuffix",
            "baseName": "brand_name_suffix",
            "type": "string",
            "format": ""
        },
        {
            "name": "listingExpirationDate",
            "baseName": "listing_expiration_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "marketingCategory",
            "baseName": "marketing_category",
            "type": "string",
            "format": ""
        },
        {
            "name": "dosageForm",
            "baseName": "dosage_form",
            "type": "string",
            "format": ""
        },
        {
            "name": "marketingStartDate",
            "baseName": "marketing_start_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "marketingEndDate",
            "baseName": "marketing_end_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "applicationNumber",
            "baseName": "application_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "pharmClass",
            "baseName": "pharm_class",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "route",
            "baseName": "route",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "activeIngredients",
            "baseName": "active_ingredients",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NdcDto.attributeTypeMap;
    }

    public constructor() {
    }
}

