/**
 * Terminology
 * Terminology API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class NpiOrganizationDto {
    'id': string;
    'businessName'?: string;
    'country'?: string;
    'state'?: string;
    'postalCode'?: string;
    'city'?: string;
    'streetLine1'?: string;
    'streetLine2'?: string;
    'phone'?: string;
    'taxonomy'?: string;
    'isDeactivated'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "businessName",
            "baseName": "business_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "postalCode",
            "baseName": "postal_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string",
            "format": ""
        },
        {
            "name": "streetLine1",
            "baseName": "street_line1",
            "type": "string",
            "format": ""
        },
        {
            "name": "streetLine2",
            "baseName": "street_line2",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "taxonomy",
            "baseName": "taxonomy",
            "type": "string",
            "format": ""
        },
        {
            "name": "isDeactivated",
            "baseName": "is_deactivated",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NpiOrganizationDto.attributeTypeMap;
    }

    public constructor() {
    }
}

